steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/product-frontend-service", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/product-frontend-service"]

  # Deploy the Docker image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args: [
        "run",
        "deploy",
        "product-frontend-service", # Name of the Cloud Run service
        "--image",
        "gcr.io/$PROJECT_ID/product-frontend-service", # Docker image URL
        "--region",
        "us-central1", # Set the region
        "--platform",
        "managed", # Cloud Run is fully managed
        "--allow-unauthenticated", # Allow public access (optional)
      ]

images:
  - "gcr.io/$PROJECT_ID/product-frontend-service"

options:
  logging: "CLOUD_LOGGING_ONLY"
